### PR TITLE
Fix/ValveAccessory

### PR DESCRIPTION
**Pull request by Tellicious**

### CODE REVIEW

**Comment by Sinclair81** [comment]
Ok, now it works!
But I still don't understand why a valve needs so many features! Active, InUse, IsConfigured...?

Then is it ready for 1.3.6?

**Comment by Tellicious** [comment]
Don't know why but the Valve it's one of the most complex services in HAP....I don't understand why it needs both Active and InUse characteristics, too...

Apart from that, I think it's ready for 1.3.6. I've been using it for some days now without any issue now. If it's working also on your installation, I'd say we're good to go

Screenshot 2023-10-28 at 22 38 43

**Comment by Sinclair81** [comment]
What is the name of Apple's document?
I would like to see if there is a newer one and read it.

And try [Homebridge-Logging](https://github.com/Sinclair81/Homebridge-Logging)!
This has slightly different settings/views in the HomeApp
It produces 2 lamps, each with 2 motion detectors integrated.
This is an example of new DynamicPlatformPlugin in Homebridge! I actually want to test the logging with it.
Attention LOGO-Platform is a StaticPlatformPlugin, there may be a few significant differences.

**Comment by Sinclair81** [comment]
```
{
            "platform": "LoggingHomebridgePlugin",
            "name": "Logging Fakegato",
            "logType": "fakegato",
            "logPort": 9998,
            "devices": [
                {
                    "name": "WZ TV SSD",
                    "type": "outlet"
                }
            ]
        }
```

**Comment by Tellicious** [comment]
> What is the name of Apple's document?
> I would like to see if there is a newer one and read it.

I attach you the version I have. It's R2 and I think it's the last published. It doesn't seem to be any longer available on the Apple website
[HAP-Specification-Non-Commercial-Version.pdf](https://github.com/Sinclair81/Homebridge-Logo-Platform/files/13198695/HAP-Specification-Non-Commercial-Version.pdf)

> And try [Homebridge-Logging](https://github.com/Sinclair81/Homebridge-Logging)!
> This has slightly different settings/views in the HomeApp
> It produces 2 lamps, each with 2 motion detectors integrated.
> This is an example of new DynamicPlatformPlugin in Homebridge! I actually want to test the logging with it.
> Attention LOGO-Platform is a StaticPlatformPlugin, there may be a few significant differences.

Wow, looks great! Can it be tested yet?

What's the main difference between DynamicPlatformPlugin and StaticPlatformPlugin? Anything major?

**Comment by Sinclair81** [comment]
> Wow, looks great! Can it be tested yet?

In Homebridge Logging there are 2 branches to test.
1. v0.0.1 - to install and test the correct logging with fakegato and or infraDB
2. test-original-accessory - for testing the multi accessory (lamp with 2 motion detectors)

> What's the main difference between DynamicPlatformPlugin and StaticPlatformPlugin? Anything major?

I don't know exactly either. I think in the DynamicPlatformPlugin the "old" accessories are automatically reloaded after restarting the Homebridge with the states they last had in the Homebridge. But I'm not a fan of that, I prefer to create it from scratch again and again according to the config.json.

**Pull request merged**
